### ISSUE TITLE
Python 3.9 compatibility master issue

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#59980]
- [ ] ????
  - [ ] seems to block on socket during tours?
- [x] dependencies
  - [x] lxml 4.3.2 doesn't compile (most recent version works)
  - [x] greenlet 0.4.15 doesn't compile (most recent version works)
  - [x] reportlab 3.5.13 doesn't work (most recent version works)
  - [x] Pillow 5.4.1 triggers warnings (most recent version works)
  - [x] freezegun 0.3.11 calls `time.clock()` which was removed in Python 3.8 (cf spulec/freezegun#296), 1.0 works
  - [x] xlrd 1.1: (unclear, `test_xls_success` fails with `Unable to load "xls" file: requires Python module "xlrd"` despite xlrd being installed, seems to work in a shell, maybe python-excel/xlrd#300 which is also a Python 3.8 / time.clock issue)
  - [x] xlrd 1.2: defusedxml doesn't quite expose the right classes / methods, which makes xlrd fall into the path of using `ElementTree.getiterator()` instead of `ElememtTree.iter()`... and the former has been removed in 3.9
    issue is known but extant in defusedxml (tiran/defusedxml#48), xlrd has gone readonly (so odds of fix are low), best options seem to be
    * swap `ensure_elementtree_imported` to directly import `lxml` and / or bypass it (set the three globals it updates directly)
    * migrate xlsx support to openpyxl which is actively maintained
- [x] APIs
  - [x] `threading.Thread.isAlive` had been undocumented for multiple versions and was removed entirely in 3.9 ([bpo-35283](https://bugs.python.org/issue37804))
- [x] opcodes
  - [x] CONTAINS_OP (`in` / `not in`)
  - [x] IS_OP (`is` / `is not`)
  - [x] LIST_EXTEND (non-empty const list literals)
    
    In Python 3.8, a non-empty list literal compiles to 

        0 LOAD_CONST               1 (1)
        2 LOAD_CONST               2 (2)
        4 LOAD_CONST               3 (3)
        6 BUILD_LIST               3

    in Python 3.9, the same compiles to

        0 BUILD_LIST               0
        2 LOAD_CONST               1 ((1, 2, 3))
        4 LIST_EXTEND              1

  - [x] SET_UPDATE (non-empty const set literals, see above)
  - [ ] LIST_TO_TUPLE ([BPO 39320](https://bugs.python.org/issue39320), also source of the above and below so "unpacking of starred values in arguments and the right hand side of assignments", do we want to allow that in safe_eval?)

        foo(*a, *b, **c, **d)

    in 3.8:

         0 LOAD_GLOBAL              0 (foo)
         2 LOAD_FAST                0 (a)
         4 LOAD_FAST                1 (b)
         6 BUILD_TUPLE_UNPACK_WITH_CALL     2
         8 LOAD_FAST                2 (c)
        10 LOAD_FAST                3 (d)
        12 BUILD_MAP_UNPACK_WITH_CALL     2
        14 CALL_FUNCTION_EX         1

    in 3.9:

         0 LOAD_GLOBAL              0 (fo
         2 BUILD_LIST               0
         4 LOAD_FAST                0 (a)
         6 LIST_EXTEND              1
         8 LOAD_FAST                1 (b)
        10 LIST_EXTEND              1
        12 LIST_TO_TUPLE
        14 BUILD_MAP                0
        16 LOAD_FAST                2 (c)
        18 DICT_MERGE               1
        20 LOAD_FAST                3 (d)
        22 DICT_MERGE               1
        24 CALL_FUNCTION_EX         1

  - [x] DICT_UPDATE
  - [x] DICT_MERGE
    used for `foo(**bar)`, which turns out we have at least one of 
  - [x] RERAISE, JUMP_IF_NOT_EXC_MATCH (exception handlers)
- [x] deprecation warnings (moar)
    - [x] Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working [res_bank.py:119] https://github.com/odoo/odoo/pull/60604/commits/8885ddf99674818b2e35e2d056c0d91e7a87fcdb
    - [x] DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working [sandbox.py:82]
        Issue fixed in pallets/jinja#867 but no release since (the tracking issue pallets/jinja#973 was closed)
        Note: apparently now fixed (since original comment), requires updating Jinja, see odoo/odoo#61103
    - [x] DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version. [survey_survey.py:440] [exhibitor.py:86]
        in 5810ea2a97d63b7302f335cc64a2101d53995297 BaseModel was registered against Set and Sequence specifically to work with random.sample, we could remove the Set registration (hopefully that doesn't work anything) leaving the Sequence one, but I'll open a bpo to ask to improve the check in case that works
    - [x] babel/util.py:70: DeprecationWarning: The parser module is deprecated and will be removed in future versions of Python
        fixed in python-babel/babel#684 but not release yet

**Comment by MjAbuz** [comment]
Same here on ubuntu 20.04,

2020-10-30 23:55:27,813 45662 WARNING server py.warnings: /usr/lib/python3/dist-packages/jinja2/sandbox.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping

The fix is done @xmo-odoo 

![Screenshot from 2020-10-31 06-10-26](https://user-images.githubusercontent.com/13909949/97767709-1c389e80-1b48-11eb-843e-9999deec30f1.png)
![Screenshot from 2020-10-31 07-08-17](https://user-images.githubusercontent.com/13909949/97767711-20fd5280-1b48-11eb-9f09-3871d6bf70cf.png)

**Comment by xmo-odoo** [comment]
Closing this as #62498 has been merged. 

New issues should be reported separately. We'll probably find a bunch if @d-fence manages to get tox working.
